export const CREATE_TOPIC_REQUEST = 'CREATE_TOPIC_REQUEST';
export const CREATE_TOPIC_FAILURE = 'CREATE_TOPIC_FAILURE';
export const CREATE_TOPIC_SUCCESS = 'CREATE_TOPIC_SUCCESS';
export const CREATE_TOPIC_DUPLICATE = 'CREATE_TOPIC_DUPLICATE';
export const GET_TOPICS = 'GET_TOPICS';
export const GET_TOPICS_REQUEST = 'GET_TOPICS_REQUEST';
export const GET_TOPICS_SUCCESS = 'GET_TOPICS_SUCCESS';
export const GET_TOPICS_FAILURE = 'GET_TOPICS_FAILURE';
export const INCREMENT_COUNT = 'INCREMENT_COUNT';
export const DECREMENT_COUNT = 'DECREMENT_COUNT';
export const DESTROY_TOPIC = 'DESTROY_TOPIC';
export const TYPING = 'TYPING';

export const CLEAR_AUTHREG_DATA = 'CLEAR_AUTHREG_DATA';
export const MANUAL_LOGIN_USER = 'MANUAL_LOGIN_USER';
export const LOGIN_SUCCESS_USER = 'LOGIN_SUCCESS_USER';
export const LOGIN_ERROR_USER = 'LOGIN_ERROR_USER';
export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_SUCCESS_USER = 'SIGNUP_SUCCESS_USER';
export const SIGNUP_ERROR_USER = 'SIGNUP_ERROR_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_SUCCESS_USER = 'LOGOUT_SUCCESS_USER';
export const LOGOUT_ERROR_USER = 'LOGOUT_ERROR_USER';

export const ROOM_REQUEST_START = 'ROOM_REQUEST_START';
export const ROOM_REQUEST_FAILURE = 'ROOM_REQUEST_FAILURE';
export const CREATE_ROOM_SUCCESS = 'CREATE_ROOM_SUCCESS';
export const GET_ROOM_SUCCESS = 'GET_ROOM_SUCCESS';
export const GET_ROOMS_SUCCESS = 'GET_ROOMS_SUCCESS';
export const INSERT_USER_BY_CODE_SUCCESS = 'INSERT_USER_BY_CODE_SUCCESS';

export const GAMES_REQUEST_START = 'GAMES_REQUEST_START';
export const GAMES_REQUEST_FAILURE = 'GAMES_REQUEST_FAILURE';
export const GET_GAMES_SUCCESS = 'GET_GAMES_SUCCESS';

export const TEAMS_REQUEST_START = 'TEAMS_REQUEST_START';
export const TEAMS_REQUEST_FAILURE = 'TEAMS_REQUEST_FAILURE';
export const GET_TEAMS_SUCCESS = 'GET_TEAMS_SUCCESS';

export const BETS_REQUEST_START = 'BETS_REQUEST_START';
export const BETS_REQUEST_FAILURE = 'BETS_REQUEST_FAILURE';
export const CREATE_BET_SUCCESS = 'CREATE_BET_SUCCESS';
export const GET_BETS_IN_ROOM_SUCCESS = 'GET_BETS_IN_ROOM_SUCCESS';
